
name:   CD-PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Install AWS CLI
      run: |
          sudo apt-get update
          sudo apt-get install -y awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Pull Image
      run: |
          docker pull vakabinto/task-master-pro:latest
          docker tag vakabinto/task-master-pro:latest vakabinto/prod-task-master-pro:latest
          docker push vakabinto/prod-task-master-pro:latest


    - name: Kubernetes deployment
      uses: danielr1996/kubectl-action@1.0.0
      with:
          kubeconfig: ${{ secrets.KUBECONFIG_PROD }}
          args: apply -f ./k8s/manifests/Deployment.yml
#
    
