name: CICD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: TRIVY FS SCAN
      run: trivy fs --format table -o fs.html .
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.1.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    -  name: Build Image
       run: |
          docker build -t vakabinto/task-master-pro:latest .
          
    - name: TRIVY IMAGE SCAN
      run: trivy image --format table -o image.html vakabinto/task-master-pro:latest
         
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build Push Image
      run: |
          docker push -t vakabinto/task-master-pro:latest
          
    - name: Kubernetes deployment
      uses: danielr1996/kubectl-action@1.0.0
      with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f deployment.yaml
    
